# Generated by Django 5.2.7 on 2025-10-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.IntegerField(verbose_name='DNI')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre localidad')),
                ('cp', models.CharField(max_length=10, verbose_name='Codigo postal')),
                ('provincia', models.CharField(max_length=50)),
            ],
        ),
    ]
