# Generated by Django 5.2.7 on 2025-10-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0002_remove_cliente_cp_remove_cliente_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cp',
            field=models.CharField(blank=True, verbose_name='cp'),
        ),
    ]
