# Generated by Django 5.2.7 on 2025-10-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0003_cliente_cp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cp',
        ),
    ]
