# Generated by Django 5.2.7 on 2025-10-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0004_remove_cliente_cp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
