# Generated by Django 5.2.7 on 2025-10-30 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0005_delete_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
                ('duenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entidad.cliente')),
            ],
        ),
    ]
